# Numpy Random Module
 

In [1]:
import numpy as np

In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a=np.arange(10)+5

In [6]:
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [7]:
np.random.shuffle(a)
print(a)

[11 13  5 12  7  8  9 10 14  6]


In [8]:
#Return values from a Standard Normal Distribution
a=np.random.randn(2,3)
print(a)

[[ 1.08362673 -0.46259526  0.76821279]
 [-0.16396684  1.91632347  0.23904566]]


In [4]:
a=np.random.randint(5,10,3)
print(a)

[8 9 5]


In [16]:
#Randomly pick one element from a array
element=np.random.choice(a)
print(element)

6


In [5]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[8 5 9]


In [2]:
np.random.seed?