In [2]:
import numpy as np
import pandas as pd

In [5]:
# Try to create a dataframe
user_data={
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(50,100,5),
    "MarksC":np.random.randint(1,100,5)
}

In [3]:
np.random.randint(1,100,5)

array([86, 76,  2, 80, 42])

In [18]:
user_data

{'MarksA': array([16, 66, 84, 99, 64]),
 'MarksB': array([52, 94, 76, 93, 64]),
 'MarksC': array([84, 86, 54, 70,  9])}

### Create col as marksA , B ,C


In [19]:
df=pd.DataFrame(user_data)

In [20]:
print(df)

   MarksA  MarksB  MarksC
0      16      52      84
1      66      94      86
2      84      76      54
3      99      93      70
4      64      64       9


In [21]:
df.head()

MarksA  MarksB  MarksC
0      16      52      84
1      66      94      86
2      84      76      54
3      99      93      70
4      64      64       9

In [22]:
df.head(n=3)

MarksA  MarksB  MarksC
0      16      52      84
1      66      94      86
2      84      76      54

In [23]:
df.columns

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')

In [24]:
df.to_csv('marks.csv')

In [25]:
my_data = pd.read_csv('marks.csv')

In [26]:
my_data

Unnamed: 0  MarksA  MarksB  MarksC
0           0      16      52      84
1           1      66      94      86
2           2      84      76      54
3           3      99      93      70
4           4      64      64       9

In [30]:
my_data=my_data.drop(columns=['Unnamed: 0'])
my_data

MarksA  MarksB  MarksC
0      16      52      84
1      66      94      86
2      84      76      54
3      99      93      70
4      64      64       9

# Pandas Basics-2

* If one value is null in marksA then count will be 4

In [31]:
my_data.describe()

MarksA     MarksB    MarksC
count   5.000000   5.000000   5.00000
mean   65.800000  75.800000  60.60000
std    31.292172  18.253767  31.57214
min    16.000000  52.000000   9.00000
25%    64.000000  64.000000  54.00000
50%    66.000000  76.000000  70.00000
75%    84.000000  93.000000  84.00000
max    99.000000  94.000000  86.00000

### To see last data TAIL is used

In [32]:
my_data.tail()

MarksA  MarksB  MarksC
0      16      52      84
1      66      94      86
2      84      76      54
3      99      93      70
4      64      64       9

In [33]:
my_data.tail(n=3)

MarksA  MarksB  MarksC
2      84      76      54
3      99      93      70
4      64      64       9

### Accesing A particular row

In [34]:
df.iloc[3]

MarksA    99
MarksB    93
MarksC    70
Name: 3, dtype: int32

### Accesing A particular row & col

In [35]:
df.iloc[3][1]

93

In [36]:
df.iloc[3,1]

93

### If we dont know certain column number

In [37]:
index=df.columns.get_loc('MarksB')
df.iloc[3,index]

93

In [38]:
index=[df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
print(index)
df.iloc[3,index]

[1, 2]


MarksB    93
MarksC    70
Name: 3, dtype: int32

We Are slicing the data for 1st 3 rows and having specific colomns

In [40]:
df.iloc[:3,index]

MarksB  MarksC
0      52      84
1      94      86
2      76      54

In [41]:
df.iloc[:3,[1,2]]

MarksB  MarksC
0      52      84
1      94      86
2      76      54

### Sorting your dataframe

In [42]:
my_data

MarksA  MarksB  MarksC
0      16      52      84
1      66      94      86
2      84      76      54
3      99      93      70
4      64      64       9

In [43]:
my_data.sort_values(by=['MarksA'])

MarksA  MarksB  MarksC
0      16      52      84
4      64      64       9
1      66      94      86
2      84      76      54
3      99      93      70

In [44]:
my_data.sort_values(by=['MarksA'],ascending=False)

MarksA  MarksB  MarksC
3      99      93      70
2      84      76      54
1      66      94      86
4      64      64       9
0      16      52      84

In [45]:
# Setting priority
my_data.sort_values(by=['MarksC','MarksA'],ascending=False)

MarksA  MarksB  MarksC
1      66      94      86
0      16      52      84
3      99      93      70
2      84      76      54
4      64      64       9

* It will give You a numpy array
* It's like having a 2d array and we perfor actions on it like we do in mupy
* We can also convert a numpy array to a dataframe

In [46]:
data_array = my_data.values

In [48]:
print(type(my_data))
print(my_data.shape)
print(data_array)
print(type(data_array))
print(data_array.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)
[[16 52 84]
 [66 94 86]
 [84 76 54]
 [99 93 70]
 [64 64  9]]
<class 'numpy.ndarray'>
(5, 3)


In [49]:
data_array[2,2]

54

In [50]:
#Numpy array to data frame

In [51]:
new_df = pd.DataFrame(data_array,dtype='int32',columns=['Physics','Chem','Maths'])

In [52]:
new_df

Physics  Chem  Maths
0       16    52     84
1       66    94     86
2       84    76     54
3       99    93     70
4       64    64      9

In [53]:
new_df.to_csv

<bound method NDFrame.to_csv of    Physics  Chem  Maths
0       16    52     84
1       66    94     86
2       84    76     54
3       99    93     70
4       64    64      9>

In [54]:
new_df.to_csv('PCM.csv')

In [55]:
# Can put header to false & index also

In [57]:
pcm1=pd.read_csv('PCM.csv')


In [58]:
print(pcm1)

   Unnamed: 0  Physics  Chem  Maths
0           0       16    52     84
1           1       66    94     86
2           2       84    76     54
3           3       99    93     70
4           4       64    64      9


In [59]:
new_df.to_csv('PCM2.csv',index=False)

In [61]:
# Notice we donot need to drop a col.
pcm2=pd.read_csv('PCM2.csv')
print(pcm2)

   Physics  Chem  Maths
0       16    52     84
1       66    94     86
2       84    76     54
3       99    93     70
4       64    64      9
