In [1]:
import numpy as np

In [2]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\DELL\AppData\Local\Programs\Python\Python38-32\python.exe -m pip install --upgrade pip' command.


In [3]:
import scipy.linalg as la

In [4]:
A = np.array([1,2,3,4,5])

In [6]:
A.ndim

1

In [7]:
A.shape

(5,)

In [8]:
X = np.array([[1,2],[3,4]])

In [9]:
X @ X

array([[ 7, 10],
       [15, 22]])

In [10]:
np.dot(X,X)

array([[ 7, 10],
       [15, 22]])

In [11]:
X*X

array([[ 1,  4],
       [ 9, 16]])

In [13]:
np.trace(X)

5

In [14]:
la.inv(X)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.linalg.det(X)

-2.0000000000000004

In [17]:
np.linalg.inv(X)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Lets solve a system of eqn
A = [[ 2 ,4, 6]
      [1, -3,-9]
      [8, 5 ,-7] ]
X = [[ x1]
      [x2]
      [x3 ]]
B = [ 4
     -11
      1  ]

In [19]:
A = np.array([[2,4,6],[1,-3,-9],[8,5,-7]])
B = np.array([4,-11,1])
print(la.solve(A,B))

[-8.52173913  9.69565217 -2.95652174]


In [20]:
# 2nd way
Ainve = la.inv(A)
np.dot(Ainve,B)

array([-8.52173913,  9.69565217, -2.95652174])

In [22]:
A = np.array([[1,2,3],[0,4,5],[1,0,6]])
eignvals , eignvector = np.linalg.eig(A)
print(eignvals)
print(eignvector)

[7.04096459 1.08849669 2.87053872]
[[ 0.47577536  0.92699459 -0.56767265]
 [ 0.75149246  0.3241272  -0.80302126]
 [ 0.45705239 -0.18873948  0.18139628]]


Carey-Hamilton Theorem

In [23]:
A = np.array([[1,2],[3,4]])

In [26]:
trace_A = np.trace(A)
detA = la.det(A)
I = np.eye(2)

In [27]:
A@A -trace_A*A+detA*I

array([[0., 0.],
       [0., 0.]])

In [28]:
Z = np.matrix([[1,2],[3,4]])

In [29]:
Z*Z

matrix([[ 7, 10],
        [15, 22]])

In [30]:
np.transpose(Z)

matrix([[1, 3],
        [2, 4]])

In [32]:
print(X)

[[1 2]
 [3 4]]


In [31]:
np.transpose(X)

array([[1, 3],
       [2, 4]])