In [1]:
import numpy as np

## Element Wise Multiplication

In [2]:
a=np.array([[1,2],[3,4]])
b=np.array([[0,2],[3,2]])

In [3]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[0 2]
 [3 2]]


In [4]:
a*b

array([[0, 4],
       [9, 8]])

## Matrix Multiplication

In [6]:
c=np.dot(a,b)

In [7]:
print(c)

[[ 6  6]
 [12 14]]


## NORMS

In [8]:
x=np.array([-5,3,10])

In [9]:
lp2=np.linalg.norm(x)
print(x)
print(lp2)

[-5  3 10]
11.575836902790225


In [12]:
y=np.array([3,4])
print(y)

lp2=np.linalg.norm(y)
print(lp2)

lp1=np.linalg.norm(y,ord=1)
print(lp1)

lpinf=np.linalg.norm(y,ord=np.inf)
print(lpinf)

[3 4]
5.0
7.0
4.0


In [13]:
A=np.array([[1,2],
           [3,4]])
np.linalg.det(A)

-2.0000000000000004

In [15]:
Ain = np.linalg.inv(A)
print(Ain)
print(np.dot(Ain , A))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [16]:
Apinv=np.linalg.pinv(A)
print(Apinv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
print(np.dot(Apinv , A))

[[ 1.0000000e+00 -8.8817842e-16]
 [-4.4408921e-16  1.0000000e+00]]


In [19]:
B=np.array([[6,8],
           [3,4]])


In [20]:
Bi=np.linalg.inv(B);
# gives error if det = 0

LinAlgError: Singular matrix

In [22]:
Bpi=np.linalg.pinv(B);
print(B)
print(Bpi)

[[6 8]
 [3 4]]
[[0.048 0.024]
 [0.064 0.032]]


In [23]:
print(np.dot(B,Bpi))

[[0.8 0.4]
 [0.4 0.2]]


## Solve A system Of Equation

In [24]:
a=np.array([[2,3],[3,1]])
b=np.array([8,5])
np.linalg.solve(a,b)

array([1., 2.])