In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,6,5])

In [4]:
print(a)

[1 2 3 6 5]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(5,)


In [7]:
b=np.array([[1],[2],[3],[4]])

In [8]:
print(b)
print(type(b))
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
(4, 1)


In [9]:
c=np.array([[1,9],[2,0],[3,7],[4,3]])

In [10]:
print(c)
print(type(c))
print(c.shape)

[[1 9]
 [2 0]
 [3 7]
 [4 3]]
<class 'numpy.ndarray'>
(4, 2)


In [11]:
print(c[2][0])

3


# create array of zeros and ones

In [12]:
a= np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(a.shape)

(3, 3)


In [15]:
b=np.ones((2,3))

In [16]:
print(b)
print(b.shape)
print(type(b))

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
<class 'numpy.ndarray'>


# Array of some constants

In [17]:
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


### Identity Matrix

In [18]:
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Random Martrix

In [19]:
e=np.random.random((2,3))
print(e)

[[0.53270316 0.92684934 0.78472966]
 [0.15786155 0.13987468 0.65476151]]


In [20]:
ran=np.random.random((2,3))*100
print(ran)

[[82.53682235 28.72656223 82.94049208]
 [ 6.47603388 51.03435714 23.30801068]]


### Slicing

In [21]:
print(ran[:,-1])

[82.94049208 23.30801068]


In [27]:
f=np.random.random((5,6))*100
print(f)

[[ 1.51325106 89.87632171 72.58662575  7.23942729 51.63250448 55.45719437]
 [98.20861869  9.57162637 49.44650506 40.85276547 80.97192416 87.42994832]
 [61.42739441 46.97826752  7.68094694  5.91514305 82.93753459 77.82392194]
 [ 1.51523515 33.70899495 67.00260331  3.37254269 96.11794859 55.47909141]
 [34.819441   32.16188394 45.54453    82.91552595 81.07920027 45.65437152]]


In [28]:
f=np.around(f)
print(f)

[[ 2. 90. 73.  7. 52. 55.]
 [98. 10. 49. 41. 81. 87.]
 [61. 47.  8.  6. 83. 78.]
 [ 2. 34. 67.  3. 96. 55.]
 [35. 32. 46. 83. 81. 46.]]


In [29]:
print(f[2:4,1:3])

[[47.  8.]
 [34. 67.]]


In [34]:
print(f[-1,-1])

46.0


### Updating value

In [37]:
z=np.zeros((3,3),dtype=np.int64)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [39]:
z[1,]=5
z[:,-1]=7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


Character Numpy

In [9]:
np.char.add("hi I a","m niice")
# concatination

array('hi I am niice', dtype='<U13')

In [10]:
a = "hi it is riya"

In [11]:
np.char.capitalize(a)

array('Hi it is riya', dtype='<U13')

In [16]:
b = "lets say its me"
np.char.join('-',b)

array('l-e-t-s- -s-a-y- -i-t-s- -m-e', dtype='<U29')

In [17]:
np.char.title(a)

array('Hi It Is Riya', dtype='<U13')

In [18]:
 m = np.char.upper(a)

In [19]:
m

array('HI IT IS RIYA', dtype='<U13')

In [20]:
np.char.lower(a)

array('hi it is riya', dtype='<U13')

In [21]:
 np.char.split(a)

array(list(['hi', 'it', 'is', 'riya']), dtype=object)

In [40]:
 np.char.strip(a,'h')

array('i it is riya', dtype='<U13')

In [41]:
 np.char.strip(a,'a')

array('hi it is riy', dtype='<U13')

In [43]:
np.char.splitlines("hello\nhow it is going\t well")

array(list(['hello', 'how it is going\t well']), dtype=object)

In [44]:
 np.char.replace(a,'i','k')

array('hk kt ks rkya', dtype='<U13')