# Mathematical Operations

In [1]:
import numpy as np

In [2]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [3]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [4]:
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


## Dot product / Matrix Multiplication

In [5]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [6]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


## multiplication of vectors 

In [7]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

In [8]:
print(a.dot(b))

30


In [9]:
print(sum(a))

10


In [10]:
print(x)
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


## Stacking of Array 

In [11]:
print(a)
b=a
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [12]:
np.stack((a,b))

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [13]:
np.stack((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [14]:
np.stack((a,b),axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [15]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [16]:
np.stack((x,y),axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
np.stack((x,y),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

## Reshaping

In [18]:
a=np.stack((a,b),axis=0)

In [19]:
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [20]:
print(a.reshape((4,2)))

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [21]:
print(a.reshape((8,1)))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [22]:
print(a.reshape((-1,4)))

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [23]:
print(a.reshape((2,-1)))

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [24]:
k=np.stack((x,y),axis=0)
k

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
k=np.stack((x,y),axis=0)
np.rollaxis(k,1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [26]:
k=np.stack((x,y),axis=0)
np.rollaxis(k,2)

array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [27]:
k=np.stack((x,y),axis=0)
np.rollaxis(k,1,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
k=np.stack((x,y),axis=0)
np.swapaxes(k,1,2)

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [29]:
for x in np.nditer(k):
    print(x)

1
2
3
4
5
6
7
8


In [30]:
print(k)
for i in np.nditer(k,order='C'):
    print(i)
for i in np.nditer(k,order='F'):
    print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8
1
5
3
7
2
6
4
8


In [31]:
Z = np.zeros((6,6),dtype=int)
Z[1::2,::2]=1
#Z[::2,,1::2]=1
Z

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0]])