# Statistical Computation

In [1]:
import numpy as np

In [7]:
a=np.arange(1,9)
print(a)

[1 2 3 4 5 6 7 8]


In [9]:
a=a.reshape((2,4))
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
print(np.min(a))

1


In [34]:
np.random.shuffle(a)

print(a)

[[5 6 7 8]
 [1 2 3 4]]


In [36]:
print(np.min(a,axis=0))
print(np.min(a,axis=1))
print(np.min(a))

[1 2 3 4]
[5 1]
1


In [37]:
print(np.mean(a))

4.5


In [39]:
b=np.array([5,3,8,2,1])

In [40]:
print(b)

[5 3 8 2 1]


In [41]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[3. 4. 5. 6.]
[6.5 2.5]


### Median 
     It is the middle most value

In [42]:
c= np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [43]:
c= np.array([1,5,4,-1,2])
print(np.median(c))


2.0


### Mean VS Average

In [44]:
print(np.mean(c))

2.2


In [45]:
print(np.average(c))

2.2


In [47]:
w=np.arange(1,6)
print(w)

[1 2 3 4 5]


In [49]:
print(np.average(c,weights=w))

1.9333333333333333


### Standard Deviation

In [50]:
u=np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

2.1354156504062622


### inbluilt

In [51]:
dev = np.std(c)
print(dev)

2.1354156504062622


### Variance

In [52]:
print(mystd ** 2)
print(dev ** 2)
print(np.var(c))

4.56
4.56
4.5600000000000005


In [63]:
a= np.array([(1,2,3,4),(3,1,4,2)]) 
c = a.flatten() 
print(c)
print(a)

[1 2 3 4 3 1 4 2]
[[1 2 3 4]
 [3 1 4 2]]


In [64]:
d=a.ravel()
print(d)
print(a)

[1 2 3 4 3 1 4 2]
[[1 2 3 4]
 [3 1 4 2]]


In [66]:
np.shape(d)

(8,)

In [71]:
x=np.copy(d)
print(x)

[0 0 0 0 0 0 0 0]


In [72]:
m = np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [73]:
x=list(m)
print(x)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [74]:
m.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [76]:
a = np.random.randint(0,15, size=(4,4))

In [77]:
print(a)

[[ 8 10 14 14]
 [ 7  1  8 14]
 [ 7 11  2  4]
 [ 4 12  9 13]]


In [78]:
a[np.where((a >= 5) & (a <= 10))]

array([ 8, 10,  7,  8,  7,  9])

In [79]:
a[(a >= 5) & (a <= 10)]

array([ 8, 10,  7,  8,  7,  9])

In [80]:
a[np.all((a >= 5) & (a <= 10))]

array([], shape=(0, 4, 4), dtype=int32)

In [81]:
a[np.any((a >= 5) & (a <= 10))]

array([[[ 8, 10, 14, 14],
        [ 7,  1,  8, 14],
        [ 7, 11,  2,  4],
        [ 4, 12,  9, 13]]])

In [82]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [83]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [84]:
np.concatenate((a,b), axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [85]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [86]:
img = np.arange(3*3*3).reshape(3,3,3)
print(img)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [87]:
img[::-1]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [88]:
img[[2,1,0], :, :]



array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [89]:
img[:, ::-1]

array([[[ 6,  7,  8],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[15, 16, 17],
        [12, 13, 14],
        [ 9, 10, 11]],

       [[24, 25, 26],
        [21, 22, 23],
        [18, 19, 20]]])